export const Categorys = [
    {
      product_id: 1,
      description: "Reebok Royal CL Jogger 2",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"Este calzado está diseñado para las actividades Indoor, si lo tuyo es el Gimnasio, en este modelo encontrarás comodidad, estabilidad, ligereza y estilo. La parte delantera del pie no muestra una sola costura, toda la capellada está tejida en una sola pieza, con puntos más abiertos en la zona donde debe respirar el pie y más ajustados donde el pie necesita sujeción. Los pasa-cordones son elastizados y el tobillo está protegido por un cuello alto y anatómico. La suela es una suela de entrenamiento por excelencia gracias a su tecnología A-Livezone que ofrece dos capas de distinta densidad en su parte media. El impacto está amortiguado por el vacío entre ambas piezas de la suela.",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatillas Deportivas",
      imgs: {
        img1: "/01.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 2,
      description: "Cartera Negras",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 3,
      description: "Lentes de Sol",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 4,
      description: "Cinturon Dama",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 5,
      description: "Bozo Hombre",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 6,
      description: "Campera Deportiva",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 7,
      description: "Pantalon Hombre",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 8,
      description: "Remera Mujer",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
    {
      product_id: 9,
      description: "Sandalias Dama",
      price_old:"$ 99.99",
      price: "$ 49.90",
      information:"",
      size:{
        item1:'36',
        item2:'37',
        item3:'38',
        item4:'39',
        item5:'40',
        item6:'41',
        item7:'42',
      },
      colour:{
        item1:'Red',
        item2:'Balck',
        item3:'White',
        item4:'Blue',
        item5:'Green/Red',
      },
      count:12,
      sku:'#21457832',
      category:'Calzado de hombre,zapatillas deportivas,calzado deportivo',
      discount_rate:"50%",
      brand_id: "1",
      category_id:"1",
      brand_description: "Zapatos",
      imgs: {
        img1: "/02.jpg",
        img2: "img/shop/categories/02.jpg",
        img3: "img/shop/categories/03.jpg",
        img4: "",
        img5: "",
      },
    },
  ];
  